### ISSUE TITLE
MAL TO MD list import

### ISSUE THREAD

**Issue by as280093** [Glagan/MyMangaDex#12]
Import all the manga if possible to mangadex list 
Like I have tons of manga on MAL but i want that list to be on md too

**Comment by Glagan** [comment]
Hi, it's a interesting feature I would like to implement, but it's complicated since I don't have a list of all MangaDex titles with their names, so I would have to *search* for each titles on your list, and **guess** if there is a corresponding title.
It's long (since I'll throttle it to avoid sending a lot of requests to MangaDex), and it's a **guess** so it **will** have false results.

With theses reasons I don't plan on doing it right now, sorry, but I might do it for another project, and I'll be sure to have it in the extension if my other project is successfull :)

**Comment by as280093** [comment]
How about adding a simple button so that when I open a manga in Mangadex if I want I can make me chapter & Vol similar as MAL same status too 
![lsjsidnd](https://user-images.githubusercontent.com/25240839/62202375-ce624300-b3a6-11e9-850b-e2d7c7a7f057.png)

**Comment by Glagan** [comment]
If you have the *Update MangaDex status* option enabled, it should update the status on MangaDex (so, add it to reading when you read) automatically when opening a chapter, and when you open any title page (or a chapter page), your progress will be saved in the **extension**, but yes the current chapter won't be saved in your list *on* MangaDex.
I don't update your MangaDex list current chapter since it does it automatically.

The only solution I see currently is to open the last chapter your read on MangaDex, I understand that it can be long, but I don't see a real solution.
I also don't really plan to update the MangaDex current chapter manually, since I don't think it is usefull if you are using this extension and so using MAL (it's redundant), and it also update itself when you read.
So if you really want to have both your MangaDex list and MAL list synced, you should do as above, if you only want the title to be in your list (and you don't care about the current chapter in your MangaDex List), just open all titles page and it will be saved in the extension, you then need to open the last chapter on MangaDex or set the status manually.

If you want the to only have it in your list (so you can use the follow page), I can update it to update the MangaDex status when you open a title page for the first time, tell me what you think :)

**Comment by as280093** [comment]
Basically I use Tachiyomi to read from mangadex it has tracking feature to MAL, kitsu, anilist 
But sometimes I do read on mD but my list is around 500+ manga and all a linked to mal but md doesn't have the list so I have to manually add each list to mD and sync it so in future if I read any chapters on MD website i should start from where i did on Tachiyomi,

**Comment by Glagan** [comment]
Sorry for the 6 months delay, but you can now Import/Export from any Service (MangaDex and MyAnimeList included) in [SyncDex](https://github.com/Glagan/SyncDex).  
It's still a beta, but everything *should* be working, if you want to try it.
