### ISSUE TITLE
[Bug] Volumes are ignored.

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#26]
For [Kengan Asura](https://mangadex.org/title/15089/kengan-asura/) with a Volume 0, MyMangaDex has trouble tracking progress in that volume and marks the chapters in both Volume 0 and Volume 1 the same (see screenshot).

![image](https://user-images.githubusercontent.com/59023762/74527179-5401a680-4f25-11ea-9145-e2b6d6c26bfa.png)

In fact, looking at the save file, it would seem that MyMangaDex completely ignores Volumes, which seems to be the problem here and might also lead to problems with other works that count per volume (though I haven't seen one like that).

**Comment by Glagan** [comment]
I actually look at volumes number but never use them, because they are not reliable, most titles don't have any, or they are set at the beginning, but not after some chapters...
I think the few titles actually using and setting volumes are too few to justify to add them to the savefile (which can already be long with a lot of titles).  
But, if I only save them if they are really defined, it might not add much, i'll look at it.
