### ISSUE TITLE
Add support for AniList

### ISSUE THREAD

**Issue by Jerrk** [Glagan/MyMangaDex#28]
I haven't seen any issues about this topic, or any mentions at all from what i can see. so i'm just looking for confirmation.

Is it possible to add support to AniList as a tracker? there are a lot of manga (especially manhwa) that don't get uploaded to MAL which can lead to significant gaps in your tracking.

**Comment by Glagan** [comment]
I don't plan to add Anilist to MyMangaDex.
I think the code I wrote didn't age well and I don't want to try to update it's root functionalities since it will basically mean rewrite it from scratch.

With that said, I already plan on haivng Anilist support in another extension I am currently making which would support both MyAnimeList and Anilist (and others..).
To make it short I'm already working on a better MyMangaDex, re-wrote from scratch that is going to update all of your lists ;)
Progress has been slow though, a reason of it is that I'm busy, but I recently started working on it again, so, one day.
