### ISSUE TITLE
Subchapters

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#36]
More and more manga in my follows use subchapters not just for extras but to also split up the chapter intentionally.
There are a few things I don't like about MyMangaDex' handling of that, so I wanted to catch your input on that before potentially making another pull request.

- Reader:
The update dialog is always shown as failed and one has to manually click update.
I'd like to add an additional check to see if it's the same chapter but a subchapter, in which case I'd display a different updated popup and only save it in local storage (no need to send to MAL)

- Follows/Title page:
Higher subchapters are generally shown either all in 'next chapter' color (follows) or 'current chapter' (title, totally unacceptable for me).
I know that finding the next chapter is impossible, because there is no guarantee that 0.1 steps are used. But at least on the title page it is possible to simply choose the next one if you go through them from the bottom. On the follows page I would like to also follow that assumption, though it means trusting that the scans release them in order). An alternative would be to save subchapters for a second pass, which would be more reliable.

**Comment by Glagan** [comment]
You can disable the confirmation dialog by disabling **Confirm Chapter** in the options, but it wouldn't show and prevent updating sometimes when you're just checking a previous chapter or something.  
The thing is, I show a confirmation dialog when the **floored** chapter is equal to the last, I do that because **MyAnimeList** only save integers.

I think I used some ``Math.floor`` in some places, for some reasons and removing them would already make things easier.
One thing missing then would be a simple check to see if the chapter is the next one for **LocalStorage** and later for **MyAnimeList** and update the later only if the difference between the two *floored* chapters is at least 1.

For the Title page, the chapters are always in order, so it would be easy to check for them.
In list pages, everything can be in any order, some titles have new groups starting them and you can have the first chapters in the middle of others chapters. (But never in the same *group*, or it's ordered, I think)

To check if the chapter is the next I do: ``Math.floor(chapter) < (Math.floor(lastChapter) + 2)`` (and ``chapter == lastChapter + 1`` if I know I have integers), changing that to ``chapter > (lastChapter + 0.1) && Math.floor(chapter) < (Math.floor(lastChapter) + 2)`` could help, but I'm not sure if it's correct by just writing it.

**Comment by cpiber** [comment]
Ad 1: Yeah, I like the confirmation dialog, but it should not be shown when it's a higher subchapter

Ad 2: I don't think removing `Math.floor` is a good idea because then going to the next chapter (e.g. `1.4` to `2.1` would not work). I think an additional check when it's the same chapter is in order

Ad 4: That would still result in the same. Currently all higher subchapters are marked as 'next' and that change would do the same (lower subchapters are already marked as 'current').

Would it be alright if I tried implementing these changes?

**Comment by Glagan** [comment]
Well, you can always try, it would only be an improvement since there is a lot of titles with subchapters, as long as the current behavior doesn't change and *normal* next chapters are still detected.  
If you have any (really any) questions you can add me on Discord (I find it easier to discuss on it).
