### ISSUE TITLE
[Enhancement] Chapter management

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#41]
Especially for Manga without a MyAnimeList Id, I think a few options for management would be nice.

- No myAnimeListID means no popup when updating, thus also no option to force update, proposal: Always show notifications (maybe add an additional line?)
- Currently no option to remove chapters from list (if saveAllOpened), proposal: Add save/remove and set current chapter icons on hover to all chapters in title

What do you think of this?

**Comment by Glagan** [comment]
Always showing notifications is not an option, I did tests when I first implemented them and it's more annoying than useful quickly.

You're right, titles without a MyAnimeList ID should follow the same rules to be be saved to LocalStorage, so a check with all related options (``saveOnlyNext``, ``saveOnlyHigher``...) should be added.  
This will remove the need for adding anything else related to chapters saving, since if you set options and confirm saving when enabled and needed, you don't need to manage what you confirmed before.

I don't really want to add buttons and such to the chapter list even if it's only in the title page.  
I always wanted MyMangaDex to be here but to not add too much to the UI to avoid having too many things on the screen (and chapter highlight is already big in the UI)

**Comment by cpiber** [comment]
Sorry, didn't get to it yesterday. So no update notifications, what about the not-updated ones? I think there still needs to be a way to force update like the synced ones.

**Comment by Glagan** [comment]
I tried to do things with the *eye* buttons but I don't remember why it didn't really work in the end, I couldn't update read chapters server side, or delete them or I don't remember exactly, but maybe I didn't try enough.  
Actually I didn't want to do what you are trying to do, so It should be possible since it seems simple.
