### ISSUE TITLE
Update notification only shows 'undefined' as manga title

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#49]
Updating works properly but the notification shows 'undefined' instead of the manga title in the text.

**Comment by Glagan** [comment]
Does it happen with a title or with all of them ? It's working for me.

**Comment by cpiber** [comment]
All of them. Using Firefox 78.0.1
Also of note: the searching notification can display it correctly.

**Comment by Glagan** [comment]
Weird, are you using some extensions that can modifiy the page or something ?  
Can you open a console while reading a chapter and execute this
```
/scans\s*,\s+(.+)\s+mangadex/i.exec(document.querySelector("meta[name='keywords']").content)
```
It's the code used to find the name.

**Comment by cpiber** [comment]
Yes, that works correctly. Somewhere `this.manga` seems to be overwritten (between searching for the MAL ID and updating)

**Comment by cpiber** [comment]
Seems to be working now, not sure what changed...

**Comment by cpiber** [comment]
After much testing, it seems that for some reason, the browser returns a full manga object from localstorage instead of what is actually saved. This means that `chapter`, `highest`, `lastRead` and `name` are overwritten with `undefined`. I have no idea why this happens or why only the first time a title is accessed...

**Comment by cpiber** [comment]
Found the problem -- there are inconsistencies with saving online.
sharedFunctions.js:291 `body.title_name = manga.name;`
However: optionsManager.js:1231 `name: element.name,` should be `name: element.title_name,`.
Also importing should only set those properties if they are defined to avoid cluttering localstorage, do you want me to add those checks?

**Comment by Glagan** [comment]
The name in `sharedFunction` *is* right, I expect `title_name` in the backend, it's not the same in the `optionsManager` but I expect just `name` there, so they both are right even though they're not the same, I don't think I'll change it since it would mean adding a version check in the backend to support both, and it's working right now so.

The `updateLocalStorage` doesn't update the receiving `manga` variable so it shouldn't set it to undefined.

You sending a request you don't need to check for `undefined` since they are erased from the body when converting to a string, but when receiving it's erasing the current name if there is one.

But none of these should make MyMangaDex display `undefined` in the notification since the only time name is set is with the function I showed in my previous comment.  
I also don't see anything assigning the name attribute (searched for `.name =` and checked all `Object.assign` calls on the whole project

**Comment by cpiber** [comment]
The problem is that when I import from online, those properties are set. optionsManager should not set the properties if they are not defined or `undefined`. They are not sent to the server, they probably also aren't received, but still they are set.

**Comment by Glagan** [comment]
Yes there should be a check for every history keys, one key also doesn't have the right name in the save, I'll add that.

This still is not related to the notification ^^

**Comment by cpiber** [comment]
Yes, it is. I have for example `"{\"45833\":{\"mal\":0,\"last\":36,\"chapters\":[36,35,34,33,32,31,30,29,28,27],\"lastTitle\":1594369187764}}"` in my save. This is wrong because when importing, `name` etc. was set and thus when fetching (myMangaDex.js:1002) the name of the manga is overwritten.

**Comment by Glagan** [comment]
Ho, my bad, I'm dumb, I didn't see that, I'm adding these checks.

**Comment by cpiber** [comment]
Your fix does nothing to prevent the creation of these undefined values. https://github.com/Glagan/MyMangaDex/blob/master/scripts/optionsManager.js#L1538 should have some checks and simply not add those keys.

**Comment by Glagan** [comment]
This is the `downloadOnline` function, it is only used to retrieve the content of the Online Save and does nothing to the local save, and all `undefined` values are removed when the object is converted to a JSON string.

**Comment by cpiber** [comment]
Yes, I noticed, that's why I deleted it again ;)
