### ISSUE TITLE
Show next unread error?

### ISSUE THREAD

**Issue by germzx** [Glagan/MyMangaDex#53]
I am describing this as a "Show Next Unread" error. Basically I have numerous manga I follow, and some of them my "last unread" is over 11 months old. This is due to starting new mangas and not just binging them up to date. So I'm presented with my Page 1 on the follows as being super concise, where if I load my bookmarked followed page and see orange or any titles there I know it's a new manga chapter. I just read those until when I press refresh I'm left with an empty followed screen (as I have it set to hide all lower chapters and only show next unread). 

I believe  the issue is when I have a series which the "next unread" is older than the amount of chapters that could fill up the follow screen had I not had the filter on, or something like this. If I travel through my followed pages, each page typically will have some series with an unread next chapter, such as 3 months ago, one from 5 months ago on the next page, 7 months on the page after that, etc. Example is below:
![screencap](https://user-images.githubusercontent.com/55007032/88014217-07c61e00-cae4-11ea-9445-76772a0e01bc.png)
Is there anyway to update the code to condense this, or is it an unavoidable issue. Obviously ideally with the current set up, all "Next unread chapter" would be condensed to pages 1 or 2, where reading till up to date would drop each series off the list until it is again updated. In that way even mangas where the chapter I'm on is 2 years old could still pop up to be read. Hope that makes sense.

**Comment by Glagan** [comment]
Sadly no there isn't, since you need previous pages to know if there is anything.

But there is already something like that in the **History** page, you can initialize it, and it will check the status of all pages in that you follow (so the same that you are in your screenshot) and highlight rows that have newer chapters.  
In your case Kenja no Mago should be a particular color and all other should be blue or green.

To test it you need to enable **Bigger History**, and go to [https://mangadex.org/history](https://mangadex.org/history), you should see a **Initialize** button then.
