### ISSUE TITLE
Online Save: Don't log out for everything

### ISSUE THREAD

**Issue by cpiber** [Glagan/MyMangaDex#60]
For some reason, FireFox DevTools sometimes blocks requests to the online save. And sometimes my internet is just bad. Neither of which is a reason to log me out. I haven't checked in the code nor tested it, but I presume there is a specific error code when the token expired or I have been logged out for some other reason. I propose to show a proper error instead (possibly with a button to resend) and only log out (with the proper notification) when it's necessary.
If you are open for this, I could start working on it in a few days.

![image](https://user-images.githubusercontent.com/59023762/94992306-69494500-0589-11eb-8500-a85b7eb3c7af.png)
![image](https://user-images.githubusercontent.com/59023762/94992323-9564c600-0589-11eb-986b-b0262ae25aae.png)

**Comment by Glagan** [comment]
Yes the default behavior on an error is to just log you out, to avoid another error on the next try, but maybe it's not really the best thing to do.  
If you want to work on it a resend button should be great.

The token doesn't expire unless it's changed manually in the options so there is no need to check for that, and there should be no error **400** if everything is setup in the options before, but it could happen.
Firefox blocking a request returns a **status** of **0** I think if you want to handle them.  
Maybe logout on error **500** should stay, since it surely means that the next request will not work, and an error message should be found in the response body in the **status** field.

**Comment by cpiber** [comment]
Alright, thanks for the information.
So normally one would stay logged in forever? No expiration of the token?
So the status is just always empty in production mode? Then I'll do that.
