### ISSUE TITLE
[Feature Suggestion] MDList-MAL sync Enchant

### ISSUE THREAD

**Issue by EcoIsMad** [Glagan/MyMangaDex#66]
I have 600 completed manga, with that many re-open and make the program update to "Reading" and then set them to "complete" manually for over 600 times is too long, i searched in these github pages if you already implemented that and found out that you didn't, so i was wondering if in your next update you can add a button or something on the MDList page that Updates all the current mangas.
after this: have a nice day, Bye

**Comment by Glagan** [comment]
Hi, sorry, I am not sure in which direction you want your list updated.

Do you have an updated **MyAnimeList** with all of your **Completed** manga in it and want them to be imported in **MangaDex**, or is it the other way around ?

If you want to do **MangaDex** -> **MyAnimeList** there is a section to do that, so I guess you want to do **MyAnimeList** -> **MangaDex**.  
If that's what you want to do, this isn't currently possible with **MyMangaDex**, but this is already in a new version which is not yet ready but should be soon(™).

But since I already wrote it in the other version I'll see if I can easily add it in **MyMangaDex**.

**Comment by Glagan** [comment]
Sorry, actually **MyMangaDex** can't do **Local Save** -> **MangaDex**, since I only save the chapter and volume for each titles, and I need the status to update it.  
Updating **MyMangaDex** to save the status everywhere is not something I want to do right now, since **MyMangaDex** will probably not receive any update other than maintenance or simple qol since I'm working on the next version.

You can wait for the next version, which I hope to put out for a beta this week or next week, where you can export in any direction more easily.
