### ISSUE TITLE
[Feature request] Update when last page is read, not first page

### ISSUE THREAD

**Issue by FishEatPork** [Glagan/MyMangaDex#70]
(Apologies if this is already a feature. If it is I have been unable to find it in the settings)
I believe it would be more useful for MAL to be updated when I read the last page of a chapter instead of the first page. If I accidentally click onto the first page of the next chapter I don't want it marked as read.
Thanks

**Comment by Glagan** [comment]
Sorry about the delay, I missed the email about this issue.  
I'll see what I can do, and there is an event for page change in the reader so it *should* be possible.

**Comment by Glagan** [comment]
I added a ``Save on last page`` option which you can find under the **Chapter page** category.

![image](https://user-images.githubusercontent.com/8447621/104471098-ba21fe00-55ba-11eb-929f-aad7faebef81.png)

It's disabled by default since I can't know what users want, and I don't want to make them think it's broken (since there is no indications), so you'll have to enable it manually.

MangaDex recommendations (from their last update) should also be supported now.

**Comment by FishEatPork** [comment]
Thanks! Works as expected.
