### ISSUE TITLE
Not really a issue, but a request

### ISSUE THREAD

**Issue by Doomwhite** [Glagan/MyMangaDex#8]
It's not really a issue, but I don't know how to get in contact so I'm using this(the pull request seems to have some requirements to use it).
Would it be possible to make the "history" hold more mangas in it? Or something that makes me have the info on my history of read chapters with a bigger limit, doesn't need to be anything fancy.

**Comment by Glagan** [comment]
You an increase the *history* size with the **Number of chapters saved** options, but don't set it too high since it can use a lot of space if you have a lot of long titles.

Are you suggesting a way to see this history and maybe edit it ?

You can also contact me on reddit: ``/u/glagan`` or on discord ``Glagan Pas Glagan Pas Lolicon#4411``.

**Comment by Doomwhite** [comment]
I've added you on Discord.

**Comment by Glagan** [comment]
I updated the extension to version 2.1 which include supports for the [/history](https://mangadex.org/history) page.
The option is disabled by default, so you need to enable it (don't forget to press *Save*).

The extension is updated for Firefox and should be soon for Chrome.
